// <auto-generated />
using ADHD_anaylzer_Admin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADHD_anaylzer_Admin.Migrations
{
    [DbContext(typeof(myDBContext))]
    [Migration("20230508112801_init7")]
    partial class init7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADHD_anaylzer_Admin.Models.ProcessedData", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HighAdhd")
                        .HasColumnType("bit");

                    b.Property<bool>("StayInPlace")
                        .HasColumnType("bit");

                    b.HasKey("SessionId", "Timestamp");

                    b.ToTable("processedData");
                });

            modelBuilder.Entity("ADHD_anaylzer_Admin.Models.QuizAnswer", b =>
                {
                    b.Property<string>("AnswerByUserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.HasKey("AnswerByUserName", "QuestionNumber");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("ADHD_anaylzer_Admin.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
